### DISCUSSION TITLE
@vitepress-theme-kt 主题的相关问题讨论

### DISCUSSION THREAD

**Discussion by Kele-Bingtang** [Kele-Bingtang/vitepress-theme-teeker#2] [Ideas]
😊 主题相关的问题都可在这讨论（包含但不限于源码，功能，Bug 等等）🤝🚀🚀🚀

**Comment by ALiaoHaolong** [comment]
佬，我是github萌新，有个小问题不太清楚想请教一下。

我提的issue，通常您会首先回复一下修复计划（比如了解、下一个版本修复），然后您会在某一次提交中修复问题，并关联这个issue，最后发布新版本，我就可以用了。

但是我注意到，我提的issue并没有被关闭，我问了一下deepseek，它说github在修复合并到主分支后会自动关闭。然而最近的1.6.0版本发布后，已经关联修复的issue并没有被自动关闭。

请问一下，这个关闭动作在github，大家一般默认约定是维护者操作还是提issue的人操作？

我看到issue页面的评论下方有个close按钮，是需要我在确认修复后点那个吗？

**Reply by Kele-Bingtang** [reply]
这个看维护者的要求吧，我这里是提 Issue 的人操作，因为我觉得提出人认为解决了才是真的解决，如果 Issue 解决了但提出人长期为关闭，我会打上 `stale` 的标签，代表长期未关闭

**Reply by ALiaoHaolong** [reply]
o~ 谢谢解答~

**Comment by ALiaoHaolong** [comment]
请问一下，Teek 官网的文档中，侧边栏的加粗标题是在哪里配置的？

<img width="1844" height="575" alt="image" src="https://github.com/user-attachments/assets/9b5edc3c-de0a-439a-acbd-f5c6c0c88a91" />

另外，vitepress-plugin-sidebar-resolve 插件是默认自带且默认启用的吗？

**Reply by ALiaoHaolong** [reply]
ok，我用 css 实现了，不用管 vitepress-plugin-sidebar-resolve 了。

css 覆盖真好用，阿巴阿巴 :)

**Reply by Kele-Bingtang** [reply]
vitepress-plugin-sidebar-resolve 插件是默认自带且默认启用的，这个加粗标题是自动读取文件名

**Reply by Kele-Bingtang** [reply]
你是要修改样式吗

**Reply by ALiaoHaolong** [reply]
> 你是要修改样式吗

是，我增加目录嵌套之后发现，生成的侧边栏中没有你这样的样式效果。

为了区分，以下将 Teek 官网的效果称为`官网效果`，我这边的效果称为`默认效果`。

默认效果对于目录名似乎只有一个字号微微变小的效果（文章字号15px，目录字号14px）：

<img width="317" height="544" alt="image" src="https://github.com/user-attachments/assets/3246a69e-8cc4-4cab-8dd1-dbd0a32da814" />

我在解析对比官网效果和默认效果的时候发现，侧边栏的 html 结构都不太一样，所以问了一下是不是插件问题。

现在我用样式覆盖的方法在默认效果上改了改（虽然和官网效果完全不同，但是我可能没能力修改侧边栏的生成过程）。

这些样式改动我还没有推送，所以我把改动的代码和改后的效果在下方给出：

```css
/* 文档风格侧边栏中，重写目录名的样式（默认样式与文章样式一样，非常的看不出来目录结构） */

/* 一级目录间增加分隔 */
.VPSidebarItem.level-1:not(.is-link):not(:first-child) h3.text {
    margin-top: 10px;
    margin-left: -10px;
    padding-top: 14px;
    padding-left: 10px;
    border-top: 1px solid var(--vp-c-divider);
}

/* 一级、二级目录文字样式 */

.VPSidebarItem.level-1:not(.is-link) h3.text,
.VPSidebarItem.level-1:not(.is-link) h4.text {
    color: var(--vp-c-text-1);
    font-weight: bold;
}
```

<img width="359" height="572" alt="image" src="https://github.com/user-attachments/assets/1bf7fc73-dd66-4323-888e-93f91cd977d1" />
